### ISSUE TITLE
Uncaught syntax error: Unexpected token

### ISSUE THREAD

**Issue by famasya** [znry27/payment_midtrans#1]
Hi, after tested this apps in odoo 12, following error raised:

```
Uncaught SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at web.assets_common.js:625
    at Function.globalEval (web.assets_common.js:625)
    at text script (web.assets_common.js:1215)
    at ajaxConvert (web.assets_common.js:1161)
    at done (web.assets_common.js:1189)
    at callback (web.assets_common.js:1212)
    at Object.send (web.assets_common.js:1212)
    at Function.ajax (web.assets_common.js:1185)
    at Function.jQuery._evalUrl (web.assets_common.js:1196)
```

Note that:
- I'm using production key
- The apps worked when using *existing users*, but **not work when using newly registered user**.

After some debugging, I noticed that the XHR call returns following values:
```

        
        <!DOCTYPE html>
        <html lang="en-US" data-website-id="1" data-oe-company-name="Trustmedis">
            <head>
                <meta charset="utf-8"/>
                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>

                
            <title>Shop - Select Payment Acquirer </title>
        
            ...
 ```

**Comment by znry27** [comment]
I can't reproduce your problem. But i have updated this repository to solve following problem :

1. Can not pay with credit card in production
2. Can not pay if customer use Shipping Address instead of Billing Address in their order

Please download newest code and see can solve your problem or not.

If problem still occurs can you provide some link, so we can analys

**Comment by famasya** [comment]
Thank you @znry27 , it worked well. I'm going to close this issue for now.
