### ISSUE TITLE
Notification isues

### ISSUE THREAD

**Issue by Khaikal0907** [znry27/payment_midtrans#2]
I have some isues when midtrans sent notification to my web and the order ant payment transaction alway pending 
![image](https://user-images.githubusercontent.com/44768457/74818989-32902880-5332-11ea-95b2-a60a021d3e2a.png)

**Comment by znry27** [comment]
What payment method that you used for testing ? Please check your midtrans dashboard and your payment status. On your screenshot, midtrans sent notification that the payment is not Done yet, so Order and Payment Transaction on Odoo still in Pending status. 

If you want to see that your Payment Transaction become Done immediately use Credit Card for Payment Testing

**Comment by Khaikal0907** [comment]
status payment di dashboard midtrans sudah trancient

**Comment by Khaikal0907** [comment]
![image](https://user-images.githubusercontent.com/44768457/75309914-02421000-5885-11ea-8236-17e688aedfe3.png)
saya menumak eror seperti itu

**Comment by znry27** [comment]
di log-nya ada notifikasi dari midtrans lagi tidak ? kalau midtrans belum kirim notifikasi lagi ya transaksinya tidak berubah.

atau coba cek status payment-nya secara manual. di repo ini belum ada, silakan tambahkan sendiri, silakan baca di [halaman midtrans](https://api-docs.midtrans.com/#direct-refund-transaction)

di screenshot diatas errornnya tidak dari module payment_midtrans ini, karena di log tertulis di website.index, di module ini tidak ada method itu

**Comment by yuniarkurniawan** [comment]
Selamat pagi mas

Untuk controller /midtrans/notification, apakah ini api yang akan digunakan pada payment notification url midtrans ?
Karena jika melihat feeback dari midtrans memunculkan pesan faild seperti gambar dibawah ini
![mirhan_4](https://user-images.githubusercontent.com/35044741/78623653-58599880-78b2-11ea-8990-ccd4355b9188.png)

Mohon pencerahannya
Terima Kasih

**Comment by znry27** [comment]
@yuniarkurniawan  ya controller itu yang dipakai. Feedback dari midtrans error apa ? error karena redirect ?

**Comment by yuniarkurniawan** [comment]
Ini masih menggunakan akun sandbox mas.

Nah mengenai feedback error itu saya kurang tau persis, untuk yang via credit card sukses, tapi untuk selain itu pada dashboard midtransnya sudah pada tahap settlement belum sampai tahap sukses. 

Tapi jika masnya sudah pernah sampe tahap sukses untuk pembayaran selain credit card ?

**Comment by znry27** [comment]
Ya. Saya sudah coba pakai pembayaran lain selain credit card di production. Lebih baik contact midtrans saja, itu error karena apa. Nanti kita betulkan sesuai feedback midtrans

**Comment by yuniarkurniawan** [comment]
Siap mas, ini lagi ditesting sama tim midtransnya dengan environment production.

Matur Nuwun Sanget

**Comment by yuniarkurniawan** [comment]
Siang Mas,

Mas saya mau tanya2 lagi. Saya sudah menggunakan : 
 AUTH_STRING = base64.b64encode((acquirer.midtrans_server_key + ':').encode('utf-8'))
 AUTH_STRING = 'Basic ' + str(AUTH_STRING.decode("utf-8"))

dan semua code sdh sama dengan yang module payment_midtrans odoo 11 - controoler (/midtrans/get_token)

Jika menggunakan akun sandbox sudah berhasil seperti biasa, tapi ketika menggunakan akun production tidak berhasil Reponse <401>. 

Tapi jika menggunakan postman sudah berhasil.

Mohon pencerahannya

Terima Kasih

Berikut terlampir pesan errornya
![Screenshot from 2020-04-14 11-41-01](https://user-images.githubusercontent.com/35044741/79186885-07631a80-7e45-11ea-9c63-b59f229faded.png)

**Comment by znry27** [comment]
Di odoo settingan Midtrans Client Key dan Midtrans Server Key sudah disetting ke Production belum ?. Sepertinya karena salah settingan saja ini.
