### ISSUE TITLE
module payment_midtrans just running with user Administrator 

### ISSUE THREAD

**Issue by chaturap** [znry27/payment_midtrans#3]
after push-button  "pay now" with user administrator
![image](https://user-images.githubusercontent.com/3143278/82200031-b43f2480-9928-11ea-84ba-8e2a8dd066a8.png)

after push-button "pay now " use a user other than the administrator
![image](https://user-images.githubusercontent.com/3143278/82200368-1730bb80-9929-11ea-8ece-683d6c9c5c69.png)

**Comment by znry27** [comment]
copy paste errornya disini, soalnya gambarnya tidak jelas.

**Comment by chaturap** [comment]
oh maaf nggak jelas y a gambarnya,
Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 642, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 698, in dispatch\n    return self._json_response(result)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 630, in _json_response\n    body = json.dumps(response)\n  File \"/usr/lib/python2.7/json/__init__.py\", line 244, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 207, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 270, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 184, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: <Response 235 bytes [302 FOUND]> is not JSON serializable\n","exception_type":"internal_error","message":"<Response 235 bytes [302 FOUND]> is not JSON serializable","name":"exceptions.TypeError","arguments":["<Response 235 bytes [302 FOUND]> is not JSON serializable"]}}

**Comment by znry27** [comment]
ini pakai versi mana ya ?
yang dari `https://github.com/dozymoe/payment_midtrans` atau yang dari sini ?

sudah beda soalnya

**Comment by chaturap** [comment]
oh iya maaf , tadi masih pakai yang daari dozymoe, barusan saya ganti dengan yang di repo sini untuk versi yg 11,
**pas coba pakai user administrator errornya**

`_> Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 642, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 684, in dispatch\n    result = self._call_function(**self.params)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 334, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/opt/odoo10/odoo/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 327, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 942, in __call__\n    return self.method(*args, **kw)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 507, in response_wrap\n    response = f(*args, **kw)\n  File \"/opt/odoo10/odoo/addons/website_sale/controllers/main.py\", line 854, in payment_transaction\n    tx = Transaction.create(tx_values)\n  File \"/opt/odoo10/odoo/addons/payment/models/payment_acquirer.py\", line 490, in create\n    custom_method_name = '%s_compute_fees' % acquirer.provider\n  File \"/opt/odoo10/odoo/odoo/fields.py\", line 934, in __get__\n    value = record._cache[self]\n  File \"/opt/odoo10/odoo/odoo/models.py\", line 5621, in __getitem__\n    return value.get() if isinstance(value, SpecialValue) else value\n  File \"/opt/odoo10/odoo/odoo/fields.py\", line 48, in get\n    raise self.exception\nMissingError: (u'Record does not exist or has been deleted.\\n\\n(Records: [17], User: 1)', None)\n","exception_type":"missing_error","message":"Record does not exist or has been deleted.\n\n(Records: [17], User: 1)\nNone","name":"odoo.exceptions.MissingError","arguments":["Record does not exist or has been deleted.\n\n(Records: [17], User: 1)",null]}}_`

**pas coba pakai user selain administrator errornya**

**web.assets_common.js:3028 Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 642, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 698, in dispatch\n    return self._json_response(result)\n  File \"/opt/odoo10/odoo/odoo/http.py\", line 630, in _json_response\n    body = json.dumps(response)\n  File \"/usr/lib/python2.7/json/__init__.py\", line 244, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 207, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 270, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 184, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: <Response 235 bytes [302 FOUND]> is not JSON serializable\n","exception_type":"internal_error","message":"<Response 235 bytes [302 FOUND]> is not JSON serializable","name":"exceptions.TypeError","arguments":["<Response 235 bytes [302 FOUND]> is not JSON serializable"]}}**

**Comment by znry27** [comment]
ada record yang sudah terhapus tapi di akses. sudah di restart service dan di upgrade modulenya ?

**Comment by chaturap** [comment]
Uninstall addons yg lama, install yg baru yg sesuai di github ini, kemudian restart

**Comment by znry27** [comment]
ini karena mengakses record dengan id 17 yang tidak ada, tidak tahu mengakses model apa. bisa upload file log-nya ? satu file utuh. 

atau sale order yang sekarang coba bayar pakai wire transfer, kemudian buat sale order lagi

**Comment by chaturap** [comment]
kebetulan odoo saya kemarin bermasalah kemudian harus saya install baru dan sudah solved, terimakasih banyak mas @znry27 ,  ditunggu addons2 lainnya ; ), misal addonss untuk moka pay atau xendit

**Comment by znry27** [comment]
Saya tidak punya akun moka pay atau xendit, jika berminat untuk buat module untuk payment gateway tersebut tolong pinjamkan saya akunnya. Kirim saja lewat email, tapi modulenya akan jadi public dan di upload di github saya.
